version: 0.2
phases:
  install:
    commands:
      - ls -la
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - echo "build"
      - aws s3 ls
      - aws s3 sync . s3://headsincloud/ --exclude "s3update/*" --exclude "terraformer/*" --exclude "lambdas/*" --only-show-errors
  post_build:
    commands:
      - echo "post_build"